name: GOAT Compile

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Obteniendo ultima version del codigo"
        uses: actions/checkout@v3

      - name: "Instalacion Java"
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: "17"

      - name: "Complilacion"   
        run: ./mvnw clean install

      - name: "Verificar paquete"
        run: ls -ltra target  

      - name: "Imagen Docker"
        run: |
          docker build -f Dockerfile . -t webgoat/test 
          docker images

      - name: "Configurar AWS Credentiales"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}    

      - name: "Cargar imagen a ECR"
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/g3i6x0d5
          docker build -t gisellemt .
          docker tag gisellemt:latest public.ecr.aws/g3i6x0d5/gisellemt:latest
          docker push public.ecr.aws/g3i6x0d5/gisellemt:latest

      - name: "Aprovisionamiento de terraform"
        run: |
          cd Terraform
          terraform init
          terraform plan -out planB
          terraform apply planB >> results_planB.txt
          ips_webgoat=$(cat results_planB.txt | grep "My_ip= " | awk '{ print $3 }' | sed 's/"//g')
          sed -i "s/IP/$ip_webgoat/g" ../Ansible/inventario

      - name: "Ejecutar ansible"
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          sudo apt update
          sudo apt install -y ansible 
          cd Ansible 
          echo "$PRIVATE_KEY" >> $HOME/key.pem
          sudo chmod 600 $HOME/key.pem
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i inventario server.yaml --become --private-key $HOME/key.pem
        continue-on-error: true

   

      

       
